name: Lint

on: [push, pull_request]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2024.11.14'

      - name: Run clj-kondo
        run: clj-kondo --lint src test
